### PR TITLE
Fix particle colors on dark background

### PR DESCRIPTION
**Pull request by br3akzero**
@topshef I have updated the colors of particles and they are now visible on a dark background. Note that I have also prettified the code but only inside of the /blackbackground directory and renamed the files to the conventional naming of html, css and js files (only in the /blackbackground directory). 

Renamed files: 
coin3.html -> index.html 
coin3.js -> main.js 
mediumclap.css -> style.css

### CODE REVIEW

**Comment by br3akzero** [comment]
I aslo want to add the colors as css variables so that they can easily be changed.

**Comment by br3akzero** [comment]
Hope you like it!

**Comment by topshef** [comment]
Thanks again, i've reverted the file naming as it would break some links and need "coin3" for reference in other tests.
https://github.com/topshef/animatedbuttons/commit/672b339cf9912794fedd5b8d24a275e1d6985d7b

**Comment by topshef** [comment]
@Denpex do you have a Hedera account for tips, or can you open one? 
See https://github.com/topshef/animatedbuttons/issues/5

**Pull request merged**
